/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.H
**     Project   : Gprs_pro
**     Processor : MC9S08DZ60MLH
**     Component : MC9S08DZ60_64
**     Version   : Component 01.075, Driver 01.35, CPU db: 3.00.021
**     Datasheet : MC9S08DZ60 Rev. 3 10/2007
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 2016-5-14, 11:34
**     Abstract  :
**         This bean "MC9S08DZ60_64" contains initialization of the
**         CPU and provides basic methods and events for CPU core
**         settings.
**     Settings  :
**
**     Contents  :
**         EnableInt  - void Cpu_EnableInt(void);
**         DisableInt - void Cpu_DisableInt(void);
**         Delay100US - void Cpu_Delay100US(word us100);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __Cpu
#define __Cpu

/* Active configuration define symbol */
#define PEcfg_08DZ60MLH 1


/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

/* MODULE Cpu. */

#ifndef __BWUserType_tPowerDownModes
#define __BWUserType_tPowerDownModes
  typedef enum {                       /*  */
    PowerDown,
    PartialPowerDown,
    StandBy
  } tPowerDownModes;
#endif

#define CPU_BUS_CLK_HZ              0x00A8C000UL /* Initial value of the bus clock frequency in Hz */

#define CPU_INSTR_CLK_HZ            0x00A8C000UL /* Initial value of the instruction clock frequency in Hz */

#define CPU_EXT_CLK_HZ              0x00A8C000UL /* Value of the main clock frequency (crystal or external clock) in Hz */
#define CPU_INT_CLK_HZ              0x7A12UL /* Value of the internal oscillator clock frequency in Hz */

#define CPU_TICK_NS                 0x5ALU /* CPU tick is a unit derived from the frequency of external clock source. If no external clock is enabled or available it is derived from the value of internal clock source. The value of this constant represents period of the clock source in ns. */

#define CPU_CORE_HCS08                 /* Specification of the core type of the selected cpu */
#define CPU_DERIVATIVE_MC9S08DZ60      /* Name of the selected cpu derivative */
#define CPU_PARTNUM_MC9S08DZ60MLH      /* Part number of the selected cpu */


/* Global variables */
extern volatile byte CCR_reg;          /* Current CCR register */


__interrupt void Cpu_ivVacmp2(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVacmp2 (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVacmp1(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVacmp1 (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVcantx(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVcantx (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVcanrx(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVcanrx (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVcanerr(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVcanerr (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVcanwu(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVcanwu (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivViic(void);
/*
** ===================================================================
**     Method      :  Cpu_ivViic (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVadc(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVadc (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVport(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVport (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVsci1tx(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVsci1tx (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVsci1rx(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVsci1rx (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVsci1err(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVsci1err (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVspi(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVspi (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVtpm2ovf(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVtpm2ovf (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVtpm2ch1(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVtpm2ch1 (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVtpm2ch0(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVtpm2ch0 (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVtpm1ovf(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVtpm1ovf (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVtpm1ch5(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVtpm1ch5 (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVtpm1ch4(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVtpm1ch4 (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVtpm1ch3(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVtpm1ch3 (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVtpm1ch2(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVtpm1ch2 (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVtpm1ch1(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVtpm1ch1 (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVtpm1ch0(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVtpm1ch0 (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVlol(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVlol (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVlvd(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVlvd (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVirq(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVirq (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Cpu_ivVswi(void);
/*
** ===================================================================
**     Method      :  Cpu_ivVswi (component MC9S08DZ60_64)
**
**     Description :
**         The method services an unhandled interrupt vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/


#define   Cpu_DisableInt()  __DI()     /* Disable interrupts */
/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S08DZ60_64)
**
**     Description :
**         Disables maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define   Cpu_EnableInt()  __EI()      /* Enable interrupts */
/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S08DZ60_64)
**
**     Description :
**         Enables maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Cpu_Delay100US(word us100);
/*
** ===================================================================
**     Method      :  Cpu_Delay100US (component MC9S08DZ60_64)
**
**     Description :
**         This method realizes software delay. The length of delay
**         is at least 100 microsecond multiply input parameter
**         [us100]. As the delay implementation is not based on real
**         clock, the delay time may be increased by interrupt
**         service routines processed during the delay. The method
**         is independent on selected speed mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         us100           - Number of 100 us delay repetitions.
**     Returns     : Nothing
** ===================================================================
*/

void PE_low_level_init(void);
/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S08DZ60_64)
**
**     Description :
**         Initializes beans and provides common register initialization. 
**         The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/* END Cpu. */

#endif /* ifndef __Cpu */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
