/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Vectors.C
**     Project   : Project2
**     Processor : MC9S08DZ60MLH
**     Version   : Component 01.075, Driver 01.35, CPU db: 3.00.021
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 2016-5-17, 13:08
**     Abstract  :
**         This bean "MC9S08DZ60_64" contains initialization of the
**         CPU and provides basic methods and events for CPU core
**         settings.
**     Settings  :
**
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


#include "Cpu.h"
#include "AS1.h"
extern near void _EntryPoint(void);

void (* near const _vect[])(void) @0xFFC0 = { /* Interrupt vector table */
         Cpu_Interrupt,                /* Int.no. 31 Vacmp2 (at C3C0)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 30 Vacmp1 (at C3C2)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 29 Vcantx (at C3C4)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 28 Vcanrx (at C3C6)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 27 Vcanerr (at C3C8)               Unassigned */
         Cpu_Interrupt,                /* Int.no. 26 Vcanwu (at C3CA)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 25 Vrtc (at C3CC)                  Unassigned */
         Cpu_Interrupt,                /* Int.no. 24 Viic (at C3CE)                  Unassigned */
         Cpu_Interrupt,                /* Int.no. 23 Vadc (at C3D0)                  Unassigned */
         Cpu_Interrupt,                /* Int.no. 22 Vport (at C3D2)                 Unassigned */
         Cpu_Interrupt,                /* Int.no. 21 Vsci2tx (at C3D4)               Unassigned */
         Cpu_Interrupt,                /* Int.no. 20 Vsci2rx (at C3D6)               Unassigned */
         Cpu_Interrupt,                /* Int.no. 19 Vsci2err (at C3D8)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 18 Vsci1tx (at C3DA)               Unassigned */
         Cpu_Interrupt,                /* Int.no. 17 Vsci1rx (at C3DC)               Unassigned */
         Cpu_Interrupt,                /* Int.no. 16 Vsci1err (at C3DE)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 15 Vspi (at C3E0)                  Unassigned */
         Cpu_Interrupt,                /* Int.no. 14 Vtpm2ovf (at C3E2)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 13 Vtpm2ch1 (at C3E4)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 12 Vtpm2ch0 (at C3E6)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 11 Vtpm1ovf (at C3E8)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 10 Vtpm1ch5 (at C3EA)              Unassigned */
         Cpu_Interrupt,                /* Int.no.  9 Vtpm1ch4 (at C3EC)              Unassigned */
         Cpu_Interrupt,                /* Int.no.  8 Vtpm1ch3 (at C3EE)              Unassigned */
         Cpu_Interrupt,                /* Int.no.  7 Vtpm1ch2 (at C3F0)              Unassigned */
         Cpu_Interrupt,                /* Int.no.  6 Vtpm1ch1 (at C3F2)              Unassigned */
         Cpu_Interrupt,                /* Int.no.  5 Vtpm1ch0 (at C3F4)              Unassigned */
         Cpu_Interrupt,                /* Int.no.  4 Vlol (at C3F6)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  3 Vlvd (at C3F8)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  2 Virq (at C3FA)                  Unassigned */
         Cpu_Interrupt                 /* Int.no.  1 Vswi (at C3FC)                  Unassigned */
};

void (* near const _vectReset[])(void) @0xFFFE = { /* Interrupt vector table */
        _EntryPoint                    /* Int.no.  0 Vreset (at FFFE)                Reset vector */
};
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/

